# --- system plugins ---
mavros_node:
  ros__parameters:
    fcu_url: "udp://:14550@"
    gcs_url: "udp://:115200@"
    tgt_system: 1
    tgt_component: 1
    heartbeat_rate: 1.0
    publish_sim_time: false