# --- system plugins ---
mavros_node:
  ros__parameters:
    fcu_url: "udp://127.0.0.1:14550@"
    gcs_url: ""
    tgt_system: 1
    tgt_component: 1
    heartbeat_rate: 1.0
    publish_sim_time: false
    # For real-hardware, use this command.
    # mavproxy.py --master=/dev/ttyUSB0,57600 --out=udp:127.0.0.1:14550